image:
  repository: gcr.io/cloudproject7x/chatbot-app
  tag: v11
  pullPolicy: Always

service:
  port: 80
  targetPort: 5000
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  host: chatbot.local
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 5
