image:
  repository: gcr.io/cloudproject7x/chatbot-app
  tag: v10
  pullPolicy: Always

service:
  port: 80
  targetPort: 5000
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  host: chatbot.local
  path: /
  pathType: Prefix

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"
