image:
  repository: gcr.io/cloudproject3-bartek/chatbot-app
  tag: echo-v4
  pullPolicy: Always


service:
  port: 80
  targetPort: 5000
  type: ClusterIP

ingress:
  enabled: true
  host: chatbot.local
  path: /
  pathType: Prefix

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 20
  periodSeconds: 10
