apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: "18.0.0"
    helm:
      values: |
        wordpressUsername: user
        wordpressPassword: bitnami123
        wordpressEmail: user@example.com
        wordpressBlogName: "My WordPress"

        ## Reduce resources for Autopilot
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi

        ## Disable persistence to avoid PVC issues
        persistence:
          enabled: false

        mariadb:
          auth:
            rootPassword: myrootpassword
            database: bitnami_wordpress
            username: bn_wordpress
            password: bitnami123
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          primary:
            persistence:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
