apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: "18.0.0"
    helm:
      values: |
        wordpressUsername: user
        wordpressPassword: bitnami123
        wordpressEmail: user@example.com
        wordpressBlogName: "My WordPress"

        ## WordPress app resource overrides
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 512Mi     # ← bumped from 256Mi

        ## Disable persistence to avoid PVC issues
        persistence:
          enabled: false

        
        mariadb:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi   # ← ensure it's ≥512Mi
          primary:
            persistence:
              enabled: false
        persistence:
          enabled: false
  destination:
    name: gke_cloudproject7x_europe-central2-b_standard-cluster
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
