apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbot-app.fullname" . }}
  labels:
    app: {{ include "chatbot-app.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "chatbot-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chatbot-app.name" . }}
    spec:
      containers:
        - name: chatbot-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
