apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-app
  namespace: chatbot
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: chatbot.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatbot-app
                port:
                  number: 5000
