{{- if .Values.persistence.model.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  labels:
    app: {{ include "chatbot-app.fullname" . }}
spec:
  storageClassName: standard     # <— explicitly request GKE’s default SC
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.model.size }}
{{- end }}
