{{- if .Values.persistence.model.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  labels:
    app: {{ include "chatbot-chart.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.model.size }}
{{- end }}
