apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.2
    helm:
      values: |
        controller:
          admissionWebhooks:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
