apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: "18.0.0"
    helm:
      values: |
        ## WordPress credentials
        wordpressUsername: user
        wordpressPassword: bitnami123
        wordpressEmail: user@example.com
        wordpressBlogName: "My WordPress"

        ## Resource sizing
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        ## Disable PVC to avoid persistence issues
        persistence:
          enabled: false

        ## MariaDB subchart overrides, including auth
        mariadb:
          auth:
            rootPassword: myrootpassword
            database: bitnami_wordpress
            username: bn_wordpress
            password: bitnami123
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          primary:
            persistence:
              enabled: false

        service:
          type: ClusterIP

        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: wordpress.local
          path: /
          pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
